### ISSUE TITLE
What is the best way to get headers at transport time?

### ISSUE THREAD

**Issue by pablocastilla** [pablocastilla/NServiceBus.Kafka#1]
Hi!

As I understand transports need the message headers before pumping the message up in the next part of the pipe. So I need to get them from the message. My problem is that kafka doesn't have any headerbag for it, I only have a byte[] payload.

Do I serialize and deserialize every message at transport level? I could use 
https://github.com/rogeralsing/Wire <-- i think now is the fastest
And a short message schema like  headers/payload

The problem is that we will have to deserialize the message twice, one in the transport and another one at serialization/deserialization time.

Do you know any better option? @danielmarbach @sfarmar

Thanks

**Comment by danielmarbach** [comment]
For historic reasons our ASQ transport does the serialize and deserialize a message envelope as well since ASQ has no concept of headers neither. It uses the endpoints serializer by default. Recently that was made pluggable. Using the endpoint serializer by default turned out to be a pretty bad choice since it is kinda obscure for the endusers and from a library perspective we shouldn't give the envelope out of control since it makes it really hard to evolve the envelope format. If you use this way stick to your opinionated choice but be aware of de risk of double serialization can lead to corruption of the payload

https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/develop/src/Transport/MessageWrapperSerializer.cs

Another option would be to binary encode the headers (they are just UTF strings) and separate it from the actual payload with a binary marker

My 2 cents

**Comment by pablocastilla** [comment]
I will go as the ASQ does. What you said seems sensible.

Thanks for the help, this is what I am looking for asking you, for sure you have a lot more experience doing NSB transports.
