### ISSUE TITLE
Not implementing callbacks

### ISSUE THREAD

**Issue by pablocastilla** [pablocastilla/NServiceBus.Kafka#10]
Hi @	danielmarbach !

From the begining I wanted the transport elastic. Services with the same name are subscribed to the same kafka topic sharing it. The problem is I think it is impossible to implement the callback feature in the sending, as the sender could not receive the message if it is scaled out because it can be processed by another endpoint.

For me it is ok and I suppose this is a normal scenario with this kind of transports.

How do you see it?

**Comment by danielmarbach** [comment]
Ah sorry never got that ping because you have a space between my name and the at sign.

Not sure it is a good idea. It is certainly possible to make this restriction. Though NSB makes the following assumptions. When you declare the endpoint with uniquely addressable queues (which is required by callbacks) you get two pumps. One for the shared queue and one or the uniquely addressable queue. In that case replies should be routed to the specific "topic".
